### ISSUE TITLE
Create Report: All the countries in a region organised by largest population to smallest.

### ISSUE THREAD

**Issue by 576125176251825152** [violin-suzutsuki/GA-SE-CW#24]
[AB#17](https://dev.azure.com/40509165/93008c05-bbba-4c74-87c9-d7d82fc408ef/_workitems/edit/17)

**Comment by SachaMillerDev** [comment]
As a Customer 
I want all the countries in a region organised by largest population to smallest
So that the user can access and use the data with ease
