### ISSUE TITLE
Create Report: All the cities in a continent organised by largest population to smallest.

### ISSUE THREAD

**Issue by 576125176251825152** [violin-suzutsuki/GA-SE-CW#30]
[AB#22](https://dev.azure.com/40509165/93008c05-bbba-4c74-87c9-d7d82fc408ef/_workitems/edit/22)

**Comment by mtjack** [comment]
As a Customer
I want all the cities in a continent organised by largest population to smallest
So that the data can be used and accessed quickly and efficiently
