### ISSUE TITLE
Create Report: All the capital cities in a region organised by largest to smallest.

### ISSUE THREAD

**Issue by 576125176251825152** [violin-suzutsuki/GA-SE-CW#41]
[AB#32](https://dev.azure.com/40509165/93008c05-bbba-4c74-87c9-d7d82fc408ef/_workitems/edit/32)

**Comment by SachaMillerDev** [comment]
As a Customer 
I want All the capital cities in a region organised by largest to smallest
So that this Data can be viewed and used quickly
