### ISSUE TITLE
Create Report: The top N populated capital cities in a continent where N is provided by the user.

### ISSUE THREAD

**Issue by 576125176251825152** [violin-suzutsuki/GA-SE-CW#43]
[AB#34](https://dev.azure.com/40509165/93008c05-bbba-4c74-87c9-d7d82fc408ef/_workitems/edit/34)

**Comment by SachaMillerDev** [comment]
As a Customer 
I want the top N populated capital cities in a continent where N is provided by the user
So that the user can use specified data from the database
