### ISSUE TITLE
Create Report: The top N populated capital cities in a region where N is provided by the user.

### ISSUE THREAD

**Issue by 576125176251825152** [violin-suzutsuki/GA-SE-CW#44]
[AB#35](https://dev.azure.com/40509165/93008c05-bbba-4c74-87c9-d7d82fc408ef/_workitems/edit/35)

**Comment by SachaMillerDev** [comment]
As a customer 
I want the top N populated capital cities in a region where N is provided by the user
So that the user can find specific data that is required
