### ISSUE TITLE
Create Report: The population of people, people living in cities, and people not living in cities in each region.

### ISSUE THREAD

**Issue by 576125176251825152** [violin-suzutsuki/GA-SE-CW#46]
[AB#38](https://dev.azure.com/40509165/93008c05-bbba-4c74-87c9-d7d82fc408ef/_workitems/edit/38)

**Comment by SachaMillerDev** [comment]
As a Customer 
I want the population of people, people living in cities, and people not living in cities in each region
So that the data can be more easily viewed and used within the application
