### ISSUE TITLE
Accessible Information - Population of the following: (world,continent,region,country,district,city)

### ISSUE THREAD

**Issue by 576125176251825152** [violin-suzutsuki/GA-SE-CW#48]
[AB#39](https://dev.azure.com/40509165/93008c05-bbba-4c74-87c9-d7d82fc408ef/_workitems/edit/39)

[AB#47](https://dev.azure.com/40509165/93008c05-bbba-4c74-87c9-d7d82fc408ef/_workitems/edit/47)

**Comment by SachaMillerDev** [comment]
As a Customer 
I want the population of the following countries to be shown (world,continent,region,country,district,city)
So that the Data can be viewed more easily in the application
