### ISSUE TITLE
Accessible Information - Provide the number of people who speak the following languages (from greatest to smallest) - Chinese,English,Hindi,Spanish, Arabic.

### ISSUE THREAD

**Issue by 576125176251825152** [violin-suzutsuki/GA-SE-CW#49]
[AB#40](https://dev.azure.com/40509165/93008c05-bbba-4c74-87c9-d7d82fc408ef/_workitems/edit/40)

[AB#46](https://dev.azure.com/40509165/93008c05-bbba-4c74-87c9-d7d82fc408ef/_workitems/edit/46)

**Comment by SachaMillerDev** [comment]
As a Customer 
I want the number of people who speak the following languages to be shown (from greatest to smallest) - Chinese,English,Hindi,Spanish, Arabic.
So that the data can be viewed within the application
